#ifndef HTTPS_CONFIG_H
#define HTTPS_CONFIG_H

// Webhook.site configuration
#define WEBHOOK_HOSTNAME "10.185.228.117"
#define WEBHOOK_TOKEN ""
#define WIFI_SSID "Zzz"
#define WIFI_PASSWORD "i6b22krm"

// HTTPS Certificate - ISRG Root X1 (Let's Encrypt Root)
#define CA_CERTXXX \
"-----BEGIN CERTIFICATE-----\n" \
"MIIFazCCA1OgAwIBAgIRAIIQz7DSQONZRGPgu2OCiwAwDQYJKoZIhvcNAQELBQAw\n" \
"TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh\n" \
"cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMTUwNjA0MTEwNDM4\n" \
"WhcNMzUwNjA0MTEwNDM4WjBPMQswCQYDVQQGEwJVUzEpMCcGA1UEChMgSW50ZXJu\n" \
"ZXQgU2VjdXJpdHkgUmVzZWFyY2ggR3JvdXAxFTATBgNVBAMTDElTUkcgUm9vdCBY\n" \
"MTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAK3oJHP0FDfzm54rVygc\n" \
"h77ct984kIxuPOZXoHj3dcKi/vVqbvYATyjb3miGbESTtrFj/RQSa78f0uoxmyF+\n" \
"0TM8ukj13Xnfs7j/EvEhmkvBioZxaUpmZmyPfjxwv60pIgbz5MDmgK7iS4+3mX6U\n" \
"A5/TR5d8mUgjU+g4rk8Kb4Mu0UlXjIB0ttov0DiNewNwIRt18jA8+o+u3dpjq+sW\n" \
"T8KOEUt+zwvo/7V3LvSye0rgTBIlDHCNAymg4VMk7BPZ7hm/ELNKjD+Jo2FR3qyH\n" \
"B5T0Y3HsLuJvW5iB4YlcNHlsdu87kGJ55tukmi8mxdAQ4Q7e2RCOFvu396j3x+UC\n" \
"B5iPNgiV5+I3lg02dZ77DnKxHZu8A/lJBdiB3QW0KtZB6awBdpUKD9jf1b0SHzUv\n" \
"KBds0pjBqAlkd25HN7rOrFleaJ1/ctaJxQZBKT5ZPt0m9STJEadao0xAH0ahmbWn\n" \
"OlFuhjuefXKnEgV4We0+UXgVCwOPjdAvBbI+e0ocS3MFEvzG6uBQE3xDk3SzynTn\n" \
"jh8BCNAw1FtxNrQHusEwMFxIt4I7mKZ9YIqioymCzLq9gwQbooMDQaHWBfEbwrbw\n" \
"qHyGO0aoSCqI3Haadr8faqU9GY/rOPNk3sgrDQoo//fb4hVC1CLQJ13hef4Y53CI\n" \
"rU7m2Ys6xt0nUW7/vGT1M0NPAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwIBBjAPBgNV\n" \
"HRMBAf8EBTADAQH/MB0GA1UdDgQWBBR5tFnme7bl5AFzgAiIyBpY9umbbjANBgkq\n" \
"hkiG9w0BAQsFAAOCAgEAVR9YqbyyqFDQDLHYGmkgJykIrGF1XIpu+ILlaS/V9lZL\n" \
"ubhzEFnTIZd+50xx+7LSYK05qAvqFyFWhfFQDlnrzuBZ6brJFe+GnY+EgPbk6ZGQ\n" \
"3BebYhtF8GaV0nxvwuo77x/Py9auJ/GpsMiu/X1+mvoiBOv/2X/qkSsisRcOj/KK\n" \
"NFtY2PwByVS5uCbMiogziUwthDyC3+6WVwW6LLv3xLfHTjuCvjHIInNzktHCgKQ5\n" \
"ORAzI4JMPJ+GslWYHb4phowim57iaztXOoJwTdwJx4nLCgdNbOhdjsnvzqvHu7Ur\n" \
"TkXWStAmzOVyyghqpZXjFaH3pO3JLF+l+/+sKAIuvtd7u+Nxe5AW0wdeRlN8NwdC\n" \
"jNPElpzVmbUq4JUagEiuTDkHzsxHpFKVK7q4+63SM1N95R1NbdWhscdCb+ZAJzVc\n" \
"oyi3B43njTOQ5yOf+1CceWxG1bQVs5ZufpsMljq4Ui0/1lvh+wjChP4kqKOJ2qxq\n" \
"4RgqsahDYVvTH9w7jXbyLeiNdd8XM2w9U/t7y0Ff/9yi0GE44Za4rF2LN9d11TPA\n" \
"mRGunUHBcnWEvgJBQl9nJEiU0Zsnvgc/ubhPgXRR4Xq37Z0j4r7g1SgEEzwxA57d\n" \
"emyPxgcYxn/eR44/KJ4EBs+lVDR3veyJm+kXQ99b21/+jh5Xos1AnX5iItreGCc=\n" \
"-----END CERTIFICATE-----\n"


// Local mTLS web cert (rename later)
#define CA_CERT \
"-----BEGIN CERTIFICATE-----\n" \
"MIIBkjCCATmgAwIBAgIUUppaMYrqszJFsn9+l2gB0zELnSIwCgYIKoZIzj0EAwIw\n" \
"HzEdMBsGA1UEAwwUQXlkaWwgQ2VudHJhbGl6ZWQgQ0EwHhcNMjUxMTEwMDkzNjA3\n" \
"WhcNMzUxMTA4MDkzNjA3WjAfMR0wGwYDVQQDDBRBeWRpbCBDZW50cmFsaXplZCBD\n" \
"QTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABJYcPf7LAqz/RwZ18ka92r6ELQqV\n" \
"0fUhUMBq2u3nM/FMssyq0k1hmx4qI0NmnsvSduPwDmWnfkoMMXIs4s6ejV+jUzBR\n" \
"MB0GA1UdDgQWBBS9T/W3V7lpygsl8mFNP/iBft1rxzAfBgNVHSMEGDAWgBS9T/W3\n" \
"V7lpygsl8mFNP/iBft1rxzAPBgNVHRMBAf8EBTADAQH/MAoGCCqGSM49BAMCA0cA\n" \
"MEQCIDb6sFb5F5/2P4qprhV7O4cucEH8g2kjV6XWPolPU4kpAiB1zhgIE7gbdPH7\n" \
"SO7jzMPVGZBUvv46qjGWS7363adJew==\n" \
"-----END CERTIFICATE-----\n"

#define CLIENT_CERT \
"-----BEGIN CERTIFICATE-----\n" \
"MIIBejCCASCgAwIBAgIUJXaCvoVVzLr1GEk0VpPUd2aRtZQwCgYIKoZIzj0EAwIw\n" \
"HzEdMBsGA1UEAwwUQXlkaWwgQ2VudHJhbGl6ZWQgQ0EwHhcNMjUxMTEwMDkzOTM2\n" \
"WhcNMjYxMTEwMDkzOTM2WjAXMRUwEwYDVQQDDAxBeWRpbCBSYXB0aWMwWTATBgcq\n" \
"hkjOPQIBBggqhkjOPQMBBwNCAATljCDkK911fWY9zl55/wcY2+0INBzh+COciYcr\n" \
"rD5CDm7rb8RU8bgwOCuEnVjN4yzZuArd37CSxkLkc3b++Mjmo0IwQDAdBgNVHQ4E\n" \
"FgQUdFOwpzf9wEMLSR61EN3Xz0y52/IwHwYDVR0jBBgwFoAUvU/1t1e5acoLJfJh\n" \
"TT/4gX7da8cwCgYIKoZIzj0EAwIDSAAwRQIhAKGTp2PnpbIz6uVD9qtMhmabmmjS\n" \
"zqYw8znUt7/AcnOMAiBe7ORFwqTobaDAeKKHk1Sv1eV4NKNFR/vQJ8tG3ZvqWw==\n" \
"-----END CERTIFICATE-----\n"

#define CLIENT_KEY \
"-----BEGIN EC PARAMETERS-----\n" \
"BggqhkjOPQMBBw==\n" \
"-----END EC PARAMETERS-----\n" \
"-----BEGIN EC PRIVATE KEY-----\n" \
"MHcCAQEEIMNABbqGa8jxHjdkE3uohQfNx0OcyO5cUyLvOkbeS/HUoAoGCCqGSM49\n" \
"AwEHoUQDQgAE5Ywg5CvddX1mPc5eef8HGNvtCDQc4fgjnImHK6w+Qg5u62/EVPG4\n" \
"MDgrhJ1YzeMs2bgK3d+wksZC5HN2/vjI5g==\n" \
"-----END EC PRIVATE KEY-----\n"

#define CLIENT_KEY_PASS ""


#endif /* HTTPS_CONFIG_H */