#ifndef HTTPS_CONFIG_H
#define HTTPS_CONFIG_H

// Webhook.site configuration
#define WEBHOOK_HOSTNAME "10.185.228.117"
#define WEBHOOK_TOKEN ""
#define WIFI_SSID "Zzz"
#define WIFI_PASSWORD "i6b22krm"

// Local mTLS web cert
#define CA_CERT \
"-----BEGIN CERTIFICATE-----\n" \
"MIIBdjCCARugAwIBAgIUP2bGak6vBjFYjxl7fBpqRFC8ai8wCgYIKoZIzj0EAwIw\n" \
"EDEOMAwGA1UEAwwFQmVuMTAwHhcNMjUxMTE1MDYwNjU2WhcNMzUxMTEzMDYwNjU2\n" \
"WjAQMQ4wDAYDVQQDDAVCZW4xMDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABIGZ\n" \
"f/5yA2ziZNfFsBVs+XRi8ixM/dPKnzaxQ/k5QDJHOvSPnSF98CcYd2urnt6zLUB+\n" \
"LvJcmAPCU4BPhnZuKy+jUzBRMB0GA1UdDgQWBBQLxkEYMR5h6Vz42MkUKFjMiDbx\n" \
"UTAfBgNVHSMEGDAWgBQLxkEYMR5h6Vz42MkUKFjMiDbxUTAPBgNVHRMBAf8EBTAD\n" \
"AQH/MAoGCCqGSM49BAMCA0kAMEYCIQDLK6gG2Yzik1PIWhs5hhaHf5e33jHR8Pc6\n" \
"GDQ1e+9l2wIhAN1sQlEKupqnOz6LP8NdVmGpytPBm0Fpr5RCNKmrdNj3\n" \
"-----END CERTIFICATE-----\n"

#define CLIENT_CERT \
"-----BEGIN CERTIFICATE-----\n" \
"MIIBdDCCARqgAwIBAgIUCvT60FFvl0VNSpVK9/CHoRlAm6QwCgYIKoZIzj0EAwIw\n" \
"EDEOMAwGA1UEAwwFQmVuMTAwHhcNMjUxMTE1MDYxMzA2WhcNMjYxMTE1MDYxMzA2\n" \
"WjBkMQswCQYDVQQGEwJVUzELMAkGA1UECAwCQ0ExFjAUBgNVBAcMDU1vdW50YWlu\n" \
"IFZpZXcxGjAYBgNVBAoMEVBpY29XIElvVCBEZXZpY2VzMRQwEgYDVQQDDAtQaWNv\n" \
"X0NsaWVudDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABP8K18/aRI51KNoNUZGC\n" \
"vDtYUrZcuL4MMmyRmgqlMb8g7ekBSxzXan+qeVgyTOwbl5IK12JQGNtvzJEjIu0d\n" \
"zoYwCgYIKoZIzj0EAwIDSAAwRQIgdL+GRCSPb7uqIEzB6Wmk/iPwBQlXongLnVOU\n" \
"XW6XHjMCIQDeOiPCQ6PmR29+zlOsqqp5LXqZ8ReMDzHsKD7tJ+VEHw==\n" \
"-----END CERTIFICATE-----\n"

#endif /* HTTPS_CONFIG_H */